examples/block_jid.py
examples/framework.py

Add default configuration file for aioxmpp examples.

---

aioxmpp/__init__.py
aioxmpp/carbons/__init__.py
aioxmpp/carbons/service.py
aioxmpp/carbons/xso.py
aioxmpp/misc/__init__.py
aioxmpp/misc/delay.py
aioxmpp/misc/forwarding.py
docs/api/changelog.rst
docs/api/public/carbons.rst
docs/api/public/index.rst
docs/api/public/misc.rst
docs/index.rst
examples/carbons_sniffer.py
tests/carbons/__init__.py
tests/carbons/test_service.py
tests/carbons/test_xso.py
tests/misc/__init__.py
tests/misc/test_delay.py
tests/misc/test_forwarding.py

This would fix #42 and also implement [XEP-0203 (Delayed Delivery)](https://xmpp.org/extensions/xep-0203.html#schema) and [XEP-0297 (Stanza Forwarding)](https://xmpp.org/extensions/xep-0297.html).

Implement Message Carbons client (and two dependent XEPs)

---

aioxmpp/avatar/service.py
tests/avatar/test_e2e.py
tests/avatar/test_service.py

Add end-to-end tests for avatar

---

aioxmpp/callbacks.py
aioxmpp/service.py
aioxmpp/stream.py
docs/api/changelog.rst
tests/test_callbacks.py
tests/test_service.py
tests/test_stream.py
tests/test_xml.py

I broke those out of #70 and they are self-contained each.

A few random patches

---

aioxmpp/plugins/xep0199.py
aioxmpp/pubsub/xso.py
aioxmpp/stanza.py
aioxmpp/xso/__init__.py
aioxmpp/xso/model.py
docs/api/changelog.rst
tests/pubsub/test_service.py
tests/pubsub/test_xso.py
tests/test_e2e.py
tests/test_stanza.py
tests/xso/test_model.py

Add strict flag to xso.Child and apply it to IQ and pubsub payloads

---

aioxmpp/roster/service.py
tests/roster/test_service.py

This should fix #56. I’m not entirely sure a race is even possible here, but better safe than sorry.

roster: fix possible race between initial processing and pushes

---

LICENSES
MANIFEST.in

Include license file in sdist tarball

---

aioxmpp/__init__.py
aioxmpp/avatar/__init__.py
aioxmpp/avatar/service.py
aioxmpp/disco/service.py
aioxmpp/entitycaps/service.py
aioxmpp/pep/service.py
aioxmpp/service.py
docs/api/changelog.rst
examples/retrieve_avatar.py
examples/set_avatar.py
tests/avatar/test_e2e.py
tests/avatar/test_service.py
tests/disco/test_service.py
tests/pep/test_service.py
tests/test_service.py

Rebase avatar on pep

---

README.rst
aioxmpp/xso/model.py
docs/api/changelog.rst
docs/index.rst
setup.py
tests/xso/test_model.py

Replace orderedset with sortedcollections

---

aioxmpp/bookmarks/__init__.py
aioxmpp/bookmarks/service.py
aioxmpp/bookmarks/xso.py
docs/api/changelog.rst
tests/bookmarks/test_service.py
tests/bookmarks/test_xso.py

Implement a highlevel interface to bookmarks

---

aioxmpp/im/conversation.py
aioxmpp/im/p2p.py
aioxmpp/misc/delay.py
aioxmpp/muc/__init__.py
aioxmpp/muc/service.py
docs/api/changelog.rst
tests/im/test_p2p.py
tests/misc/test_delay.py
tests/muc/test_e2e.py
tests/muc/test_service.py

Transitional MUC occupants during history replay

---

aioxmpp/chatstates/__init__.py
aioxmpp/chatstates/utils.py
aioxmpp/chatstates/xso.py
aioxmpp/xso/model.py
docs/api/public/chatstates.rst
docs/api/public/index.rst
tests/chatstates/__init__.py
tests/chatstates/test_utils.py
tests/chatstates/test_xso.py
tests/pubsub/test_xso.py
tests/xso/test_model.py

Implement XEP-0085

---

aioxmpp/im/conversation.py
aioxmpp/im/p2p.py
tests/im/test_conversation.py
tests/im/test_p2p.py

* add the LEAVE feature
* implement .features for p2p conversation
* minor documentation fixes

Some fixes for im.conversation

---

README.rst
aioxmpp/__init__.py
aioxmpp/_version.py
aioxmpp/service.py
aioxmpp/version/__init__.py
aioxmpp/version/service.py
aioxmpp/version/xso.py
aioxmpp/xso/model.py
docs/api/changelog.rst
docs/api/public/index.rst
docs/conf.py
docs/index.rst
examples/query_versions.py
setup.py
tests/pubsub/test_service.py
tests/test_service.py
tests/version/__init__.py
tests/version/test_e2e.py
tests/version/test_service.py
tests/version/test_xso.py

Fixes #167.
As the title states :).

Implement XEP-0092 (Software Version)

---

aioxmpp/__init__.py
aioxmpp/mdr/__init__.py
aioxmpp/mdr/service.py
aioxmpp/tracking.py
docs/api/changelog.rst
docs/api/public/index.rst
docs/api/public/mdr.rst
docs/glossary.rst
docs/index.rst
tests/mdr/test_e2e.py
tests/mdr/test_service.py
tests/test_tracking.py

* Include documentation for the mdr (XEP-0184) module and make it more usable.
* Add e2e tests for the mdr module.
* Fix #166.

Improve message tracking and delivery receipts

---

setup.py

setup: fix version check for odd versions of setuptools

---

aioxmpp/forms/fields.py
aioxmpp/forms/form.py
aioxmpp/forms/xso.py
docs/api/changelog.rst
tests/forms/test_fields.py
tests/forms/test_form.py
tests/forms/test_xso.py

Specifically, this fixes #200, fixes #201, fixes #202 and addresses other issues.

Fixes to the Data Forms implementation

---

aioxmpp/im/conversation.py
aioxmpp/muc/__init__.py
aioxmpp/muc/service.py
aioxmpp/muc/xso.py
docs/api/changelog.rst
docs/index.rst
tests/muc/test_e2e.py
tests/muc/test_service.py
tests/muc/test_xso.py

Support for sending and receiving MUC invitations.
Fixes #154.

MUC invitation support

---

aioxmpp/avatar/service.py
tests/avatar/test_service.py

Fix equality comparison for AvatarPubsubDescriptor

---

aioxmpp/im/p2p.py
docs/api/changelog.rst
tests/im/test_p2p.py

im-p2p: fix exception when leaving conversations

---

aioxmpp/e2etest/__init__.py
aioxmpp/e2etest/provision.py

e2etest: Implement AnyProvisioner

---

aioxmpp/presence/service.py
tests/presence/test_service.py

presence: ignore presence from account in PresenceClient

---

aioxmpp/connector.py
tests/test_connector.py

Fix TLS certificate verification of unicode domains

---

aioxmpp/nonza.py
aioxmpp/stream.py
docs/api/changelog.rst
tests/test_stream.py

stream: support for stanza counter when resumption <failed/>

---

aioxmpp/security_layer.py
docs/api/changelog.rst
docs/conf.py
tests/test_security_layer.py

security_layer: support ssl_context_factory argument on make

---

aioxmpp/misc/__init__.py
aioxmpp/misc/openpgp_legacy.py
docs/api/changelog.rst
docs/index.rst
tests/misc/test_openpgp_legacy.py

misc: support for XEP-0027 schema

---

aioxmpp/forms/xso.py
aioxmpp/presence/service.py
aioxmpp/pubsub/service.py
aioxmpp/roster/xso.py
aioxmpp/security_layer.py
aioxmpp/service.py
aioxmpp/xso/model.py
docs/api/changelog.rst
docs/sphinx-data/extensions/aioxmppspecific.py
docs/user-guide/installation.rst

Fixes the deprecation warning issue and also some other errors which have accumulated in the documentation over time.
Fixes #26.

docs: fix sphinx warnings

---

aioxmpp/muc/self_ping.py
aioxmpp/muc/service.py
tests/muc/test_self_ping.py
tests/muc/test_service.py

This will help to figure out when/if something goes wrong with the
self ping mechanism.

muc.self_ping: add debug logs to the monitor and pinger

---

aioxmpp/__init__.py
aioxmpp/structs.py
docs/api/changelog.rst
docs/index.rst
tests/test_structs.py

Implement JID escaping and unescaping functions

---

aioxmpp/__init__.py
aioxmpp/misc/__init__.py
aioxmpp/misc/lmc.py
docs/api/changelog.rst
docs/index.rst
tests/misc/test_replace.py

Add support for XEP-0308

---

aioxmpp/structs.py
docs/api/changelog.rst
tests/test_structs.py

Adds a simple test case which fails at the moment

test_structs: Add jid escape testcase
