aioxmpp/node.py, aioxmpp/service.py, aioxmpp/xso/model.py, tests/test_node.py, tests/test_service.py
* fixes a aioxmpp.Client.summon bug, where services where loaded
in the wrong order
* makes comparison of the aioxmpp.Service subclasses a topological order
consistent with the dependency order of the services (note: this order
can change radically when a new service is declared, the relative
order of independent services is not defined!)
=> Fix the toposort of aioxmpp.Service subclasses

aioxmpp/stream.py, docs/api/changelog.rst, tests/test_highlevel.py, tests/test_stream.py
* SM counters now wrap modulo 2**32 as is specified by
XEP-0198
=> Fix SM counter overflow behaviour

aioxmpp/avatar/__init__.py, aioxmpp/avatar/service.py, aioxmpp/avatar/xso.py, aioxmpp/e2etest/__init__.py, examples/retrieve_avatar.py, examples/set_avatar.py, tests/avatar/test_service.py, tests/avatar/test_xso.py, tests/pubsub/test_service.py
* fix the set_avatar.py example
* some refactoring
* fix some documentation issues
* fix style issues
* fix `get_avatar_metdata(..., require_fresh=True)`
* fixes #59
=> Further avatar fixes and improvements

aioxmpp/connector.py, aioxmpp/node.py, aioxmpp/xml.py, docs/api/changelog.rst, tests/test_connector.py, tests/test_node.py, tests/test_xml.py
* We now call flush from XMPPXMLGenerator, which makes the DebugWrapper used to show debug output work again (it relies on flush being called to assemble the output)
* The logger of the XMLStream is now put below the logger of the Client, improving debug output readability a lot (especially for e2etests)
=> Improve debugability of XMLStream

aioxmpp/disco/service.py, aioxmpp/entitycaps/service.py, docs/api/changelog.rst, tests/disco/test_service.py, tests/entitycaps/test_e2e.py, tests/entitycaps/test_service.py
It was broken since e4388f7!
Should we release v0.8.1 due to this? We really need e2e tests for ecaps by the way, that would’ve been caught by those.
The impact is that outgoing capabilities are not generated, even though we advertise the feature.
=> Fix EntityCapsService

aioxmpp/e2etest/provision.py, tests/blocking/test_e2e.py, utils/prosody-cfg/0.10/prosody.cfg.lua, utils/prosody-cfg/0.9/link.sh, utils/prosody-cfg/0.9/prosody.cfg.lua, utils/prosody-cfg/trunk/prosody.cfg.lua
Closes #78.
This needs a change in the prosody config so that a provider of XEP-0191 is loaded.
=> Add end-to-end tests for aioxmpp.blocking

tests/avatar/test_e2e.py
Remove assertions from asynchronously called code.
=> Fix end-to-end test for the avatar service

aioxmpp/bookmarks/__init__.py, aioxmpp/bookmarks/service.py, aioxmpp/bookmarks/xso.py, aioxmpp/private_xml/__init__.py, aioxmpp/private_xml/service.py, aioxmpp/private_xml/xso.py, docs/api/changelog.rst, docs/api/public/bookmarks.rst, docs/api/public/index.rst, docs/api/public/private_xml.rst, examples/get_bookmarks_raw.py, tests/bookmarks/test_service.py, tests/bookmarks/test_xso.py, tests/private_xml/test_e2e.py, tests/private_xml/test_service.py, tests/private_xml/test_xso.py
Closes #50 and #48.
Note: The design of the bookmark service was reworked to be radically simple. It is out of scope for aioxmpp to solve the subtle issues when modifying bookmarks. However, groundwork has been laid
and explained in the documentation: The XSOs representing bookmarks have a definition of equality, this allows the use of by value list operations to modify Storage.bookmarks.
=> Implement client side support for private XML storage and bookmarks.

setup.py
Update our setup.py to use the `Topic :: Internet :: XMPP` classifier.
See <https://github.com/pypa/warehouse/issues/1287> and <https://pypi.python.org/pypi?%3Aaction=list_classifiers>.
=> Add the new `Topic :: Internet :: XMPP` classifier

aioxmpp/roster/service.py, aioxmpp/testutils.py, docs/api/changelog.rst, tests/roster/test_service.py
The main point is to provide ``on_group_added`` and ``on_group_removed`` signals in ``RosterClient``. While implementing that, I stumbled across the fact that the ``groups`` data structure does not get updated when an entry is removed from the roster during the initial roster update.
=> Fixes and features for RFC 6121 roster implementation

aioxmpp/entitycaps/__init__.py, aioxmpp/entitycaps/caps115.py, aioxmpp/entitycaps/common.py, aioxmpp/entitycaps/service.py, aioxmpp/entitycaps/xso.py, aioxmpp/testutils.py, tests/entitycaps/test_caps115.py, tests/entitycaps/test_e2e.py, tests/entitycaps/test_service.py, tests/entitycaps/test_xso.py, tests/test_testutils.py
This is the first step towards #76. It doesn’t address any issues with entitycaps support as-is, but refactors for easier improvements later on.
=> Refactor EntityCapsService to decouple XEP-0115-specifics from core

aioxmpp/disco/__init__.py, aioxmpp/disco/service.py, aioxmpp/e2etest/__init__.py, aioxmpp/entitycaps/__init__.py, aioxmpp/entitycaps/caps390.py, aioxmpp/entitycaps/service.py, aioxmpp/entitycaps/xso.py, aioxmpp/hashes.py, aioxmpp/misc/__init__.py, docs/api/changelog.rst, docs/api/public/hashes.rst, docs/api/public/index.rst, docs/index.rst, tests/avatar/test_e2e.py, tests/disco/test_service.py, tests/entitycaps/test_caps390.py, tests/entitycaps/test_e2e.py, tests/entitycaps/test_service.py, tests/entitycaps/test_xso.py, tests/test_hashes.py
This depends on #97!
This implements support for emitting and processing XEP-0390 capabilities, as well as the possibility to turn emission and processing for XEP-0115 and XEP-0390 on and off respectively (they both default to "on").
The following features are still missing and will be implemented in an upcoming PR:
* ~~Keeping the last 3 capability hash sets available for querying (including those from XEP-0115)~~
* Inbound and outbound rate limits
=> Support for XEP-0390 (Entity Capabilities 2.0)

aioxmpp/cache.py, aioxmpp/disco/service.py, aioxmpp/entitycaps/service.py, aioxmpp/utils.py, docs/api/changelog.rst, docs/api/internal/cache.rst, docs/api/internal/index.rst, tests/disco/test_service.py, tests/entitycaps/test_e2e.py, tests/entitycaps/test_service.py, tests/test_cache.py, tests/test_utils.py
Fixes #100 and reduces overall footprint of entitycaps.
Key changes:
* ``EntityCapsService`` now uses ``LazyTask`` (also new in this PR) instead of ``asyncio.async`` for its lookups. ``LazyTask`` essentially spawns the task only when the first attempt to await the task is made. This reduces the traffic during (re-)connects while still having the benefits of entity capabilities: at the point the query is made, the most recent caps are looked up in the cache and only on a miss the query is fired.
* ``DiscoClient`` now uses ``LRUDict`` (new in this PR) for its caches. This means that excess entries are removed with a least-recently-used policy. This prevents the ``DiscoClient`` cache from filling all the memory with ``LazyTask`` objects (formely just ``asyncio.Task`` objects) from …
=> Limit size of DiscoClient caches and defer EntityCapsService lookups

aioxmpp/node.py, aioxmpp/nonza.py, aioxmpp/stream.py, aioxmpp/xso/model.py, docs/api/changelog.rst, docs/user-guide/pitfalls.rst, tests/test_node.py, tests/test_nonza.py, tests/test_stream.py, tests/xso/test_model.py
Fixes #114.
In addition fixes a bug uncovered in XSO while adding validators to the SMEnable{,d} nonzas: The validators were run on default values despite the opposite being documented.
=> Add attribute to control the maximum lifetime of a Stream Management session at the server

aioxmpp/im/conversation.py, aioxmpp/muc/service.py, aioxmpp/tracking.py, docs/api/changelog.rst, tests/muc/test_e2e.py, tests/muc/test_service.py, tests/test_tracking.py
* Generate trackers for sent messages we receive via Carbons
* Fix missing emission of ``on_message`` from MUC ``send_message_tracked``.
* Fix a traceback which can happen in real-life when using MUC.
* ``send_message_tracked`` of MUC was a coroutine, even though that was not intended by AbstractConversation
=> Improve the AbstractConversation API regarding tracking

aioxmpp/service.py, docs/api/changelog.rst, tests/test_service.py
As discovered by @sebastianriese while working on #125.
=> service: fix is_{dep,attr}signal_handler with defer=True

aioxmpp/adhoc/service.py, aioxmpp/callbacks.py, aioxmpp/service.py, aioxmpp/stream.py, docs/api/changelog.rst, docs/user-guide/quickstart.rst, tests/disco/test_service.py, tests/entitycaps/test_e2e.py, tests/test_callbacks.py, tests/test_service.py, tests/test_stream.py, tests/test_testutils.py
Essentially what is written in #143:
* Rename ``{un,}register_iq_request{coro => handler}`` and support plain functions returning awaitables as handlers.
* Allow a callback returning an awaitable (or None) when ``send()``-ing IQ requests. The callback is invoked.
* Tack nice warnings and notes on things to explain the reasoning and warn against excessive use of these features.
* Adapt downstream tooling (like the ``iq_handler`` decorator).
Implements/fixes #143.
=> Synchronous callbacks for IQ handlers

aioxmpp/avatar/service.py, aioxmpp/im/__init__.py, aioxmpp/im/conversation.py, aioxmpp/im/p2p.py, aioxmpp/im/service.py, aioxmpp/muc/service.py, aioxmpp/testutils.py, docs/api/changelog.rst, tests/im/test_p2p.py, tests/im/test_service.py, tests/muc/test_e2e.py, tests/muc/test_service.py, tests/test_testutils.py
So I had those in the pipeline for some time now. They came into existance during development on MLXC.
The spirit is the following:
Conversation construction is a bit tricky, because normally we’d want to call a method on the respective Conversation Service (e.g. join()) and store the result away somewhere. This is the easy part. Things get funny with "spontaneous" conversations like the one-on-one implementation has (e.g. when a contact spontaneously starts messaging you): in that case, you have to rely on some event from the conversation service.
Before, there was no such event. There was, of course, the ``on_conversation_new`` event, but this is not usable: one cannot distinguish between spontaneous and non-spontaneous (locally triggered) conversations. Thus one would have to use that …
=> Rework conversation join/new events

aioxmpp/stanza.py, aioxmpp/xso/__init__.py, aioxmpp/xso/model.py, docs/api/changelog.rst, tests/test_stanza.py, tests/xso/test_model.py
Fixes #140, #148.
This introduces a new keyword argument on the text parsing XSO types, ``erroneous_as_absent``. This affects ``Attr``, ``ChildText`` and ``Text``. It defaults to false (the previous behaviour). If set to true, ValueError and TypeError when invoking ``type_.parse`` are ignored and the default value (if any) is used. If no default is set, the attribute behaves as if it was unset.
=> Support for defaulting when an attribute / child text fails to parse

aioxmpp/cache.py, benchmarks/test_cache.py, tests/test_cache.py
* before insertion was O(maxsize*log(maxsize)) which got unacceptably slow
even for maxsize = 1000
* now we got O(1) retrieval and insertion (getting is now about 1.5 times
slower!)
* the code is inspired by functools.lru_cache
=> Make insertion O(1) for aioxmpp.cache.LRUDict

aioxmpp/avatar/__init__.py, aioxmpp/avatar/service.py, aioxmpp/avatar/xso.py, aioxmpp/errors.py, aioxmpp/pep/service.py, aioxmpp/utils.py, aioxmpp/vcard/__init__.py, aioxmpp/vcard/service.py, aioxmpp/vcard/xso.py, docs/api/changelog.rst, docs/api/public/index.rst, docs/api/public/vcard.rst, examples/README.rst, examples/get_vcard.py, examples/retrieve_avatar.py, tests/avatar/test_e2e.py, tests/avatar/test_service.py, tests/avatar/test_xso.py, tests/test_utils.py, tests/vcard/__init__.py, tests/vcard/test_service.py, tests/vcard/test_xso.py
This fixes #138.
I am unsure about two points, but I think a review might help to clarify them:
* how to prevent races that result in inconsistent metadata (between calls of get_avatar_metadata
and the handlers for avatar pushes) – this would be easy if we would have a stanza serial number
and add this info to the cache as "age" information. Another partial solution would be to bundle 
requests.
* is the fallback behaviour on vCard avatars done correctly (in which cases do we want to use the 
fallback). This might take some testing with real implementations to get right (as the responses we
get may well depend on the XMPP server and client of the peer).
=> Implement vCard and vCard Based Avatars

aioxmpp/protocol.py, aioxmpp/testutils.py, docs/api/changelog.rst, tests/test_protocol.py
This is needed for proper error handling. Without this fix, the connectors (which wait for the features_future) would block indefinitely if an error happens before the stream features are received.
Another way to fix that would’ve been to make the connectors *also* listen for error_futures from the stream. I consider this solution cleaner though.
=> Propagate pre-stream-features errors to features_future

aioxmpp/security_layer.py
Not sure if it is correct, that we also send ALPN when we do STARTTLS, if this should be an issue I will fix it.
=> Implement ALPN support

aioxmpp/connector.py, aioxmpp/security_layer.py, tests/test_connector.py, tests/test_security_layer.py
Fixes #170.
* ALPN support now lives in the connector module
* improved checking for ALPN availablity (pyOpenSSL raises
NotImplementedError if the underlying OpenSSL does not
support ALPN)
* warnings if ALPN is required but not available
NOTE: e2e tests for the ALPN support in the connector would be nice.
=> connector/security_layer: Move ALPN support to connector

aioxmpp/misc/__init__.py, aioxmpp/misc/pars.py, docs/api/changelog.rst, tests/misc/test_pars.py
This adds what is necessary on the aioxmpp side to support XEP 379 and therefore closes #104.
=> misc: Add XSO definitions for XEP-0379

aioxmpp/__init__.py, aioxmpp/avatar/service.py, aioxmpp/callbacks.py, aioxmpp/disco/service.py, aioxmpp/e2etest/provision.py, aioxmpp/entitycaps/service.py, aioxmpp/node.py, aioxmpp/protocol.py, aioxmpp/stream.py, aioxmpp/tasks.py, aioxmpp/testutils.py, aioxmpp/utils.py, examples/adhoc_browser/utils.py, examples/list_presence.py, tests/disco/test_service.py, tests/entitycaps/test_service.py, tests/muc/test_service.py, tests/roster/test_service.py, tests/test_connector.py, tests/test_node.py, tests/test_protocol.py, tests/test_statemachine.py, tests/test_stream.py, tests/test_tasks.py, tests/test_testutils.py, tests/test_utils.py
Closes #161 
Made the changes specified in #161, all tests for aioxmpp test runner passed with the asyncio.ensure_future instead of asyncio.async. 
I have only executed the tests found in the project, I am unsure if this is enough to know if the change is working or not. Let me know if anything needs to be changed or added.
=> Replace use of asyncio.async with asyncio.ensure_future and provide fallback

aioxmpp/version/service.py, tests/version/test_e2e.py, tests/version/test_service.py
Fixes #168.
``version`` is now generated as per ``self._version or "unspecified"`` and if ``name`` is None, ``service-unavailable`` is returned. Also, the defaults for both are set to None now.
=> version: always emit name and version or return service-unavailable

aioxmpp/node.py, aioxmpp/rfc3921.py, docs/api/changelog.rst, tests/test_node.py, tests/test_rfc3921.py
=> Make legacy session negotiation optional if supported by the server

aioxmpp/xml.py, benchmarks/test_xml.py, tests/test_xml.py
Fixes #193 and fixes #195.
This has the downside of slowing down XML serialisation. There are opportunities for future optimization, but we’ll just do that at some other time.
=> Remove libxml2 dependency

aioxmpp/disco/service.py, docs/api/changelog.rst, tests/disco/test_service.py
Useful if you do, say, scans of a lot of MUCs and want to have a point at which the cache is flushed for the next round, without sacrificing the caching while scanning.
=> disco: add flush_cache method

aioxmpp/disco/service.py, docs/api/changelog.rst, tests/disco/test_service.py
Currently, there’s no way (if you want to use the default "client"/"bot" identity) to set names for it without first adding a new identity, removing the default identity, then adding the identity you actually want and remove the identity you added first (due to limitations applied by the Node class).
This fixes that by allowing to update the names of an existing identity.
=> disco: add method to update names of an identity without removing/readding it

aioxmpp/security_layer.py, docs/api/changelog.rst, tests/test_security_layer.py
This allows the application to react to malformed credentials.
Follow up work will be done in #217.
=> security_layer: handle ValueError from aiosasl

aioxmpp/muc/service.py, aioxmpp/muc/xso.py, docs/api/changelog.rst, tests/muc/test_service.py
=> muc: Always strip the resource part of the direct_jid of a member

aioxmpp/stanza.py, docs/api/changelog.rst, tests/test_stanza.py
Those descriptors are undocumented and probably unused. They can easily be replaced by patching descriptors to the classes instead, which results in more readable code.
=> Remove Message.ext and Presence.ext

aioxmpp/ibr/__init__.py, aioxmpp/ibr/service.py, aioxmpp/ibr/xso.py, docs/api/public/index.rst, docs/api/public/version.rst, docs/glossary.rst, docs/index.rst
* include api/pulblic/ibr.rst in the toctree
* make the ibr documentation render properly
* add api/public/version.rst
* add the glossary to the toctree
Note: My sphinx does not seem to be happy with the references generated by `` :xep:`xxx` ``. It emits warnings like
>  /home/sebi/progs/projects/aioxmpp/docs/user-guide/quickstart.rst:411: WARNING: 4 column based index found. It might be a bug of extensions you use: [('single', 'XMPP Extension Protocols (XEPs); XEP 0092', 'index-3', '')]
=> Fix various documentation errors

aioxmpp/xso/__init__.py, aioxmpp/xso/model.py, docs/api/changelog.rst, tests/xso/test___init__.py, tests/xso/test_model.py
ChildTextMap now can be constructed from either an XSO or a tag.
If a tag is given a matching XSO is constructed on the fly.
Merging this PR closes #264.
=> Make ChildTextMap accept either a tag or an XSO

aioxmpp/xso/model.py, docs/api/changelog.rst, tests/xso/test_model.py
**Needs backport to 0.10!**
guard() was incorrectly counting the depth when either of the following was true:
- the error occured inside the first "start" event on which guard() is used: in that case, guard() would fail to swallow the corresponding "end" event.
- after an error, further elements appear in the stream before the guard()-ed element is over. in that case, guard() would fail to account for the "start" events caused by those events, and thus let its depth counter go entirely out-of-sync with the XML tree
If this flaw is combined with the use of a supressing ``xso_error_handler``, it is possible to make elements appear higher up in the XML stream tree than they actually are; this implies that it is possible to inject elements in the XML stream.
It requires very specific …
=> xso: fix parser error handling

aioxmpp/service.py, aioxmpp/stream.py, docs/api/changelog.rst, tests/disco/test_service.py, tests/test_dispatcher.py, tests/test_service.py, tests/test_stream.py
This PR does the following things:
* Allow handlers to take additional keyword arguments.
* Use this to add an with_send_reply flag that can be given to IQ handler and then passes an
as extra argument a function that can be used to send IQ responses *before* the handler function
terminates. The automatic response will be suppressed by this.
=> Allow IQ handlers to respond early

aioxmpp/hashes.py, docs/api/changelog.rst, tests/test_hashes.py
* Support for the hash-used element (used e.g. by jingle file transfer) in addition to hash
* A service that automatically registeres the disco features corresponding to supported hash functions and has tooling to determine hash functions supported in common with another entity.
=> hashes: Implement a service and support hashes-used

aioxmpp/node.py, aioxmpp/service.py, docs/api/changelog.rst, tests/adhoc/test_service.py, tests/avatar/test_service.py, tests/blocking/test_service.py, tests/carbons/test_service.py, tests/entitycaps/test_service.py, tests/im/test_p2p.py, tests/pep/test_service.py, tests/pubsub/test_service.py, tests/shim/test_service.py, tests/test_node.py, tests/test_service.py
* The Service classes no longer define `__lt__` and `__gt__`
* There now is a property `order_index` and sorting (summoned)
Service *instances* by the `order_index` will give a topological
sort with respect to their dependencies.
* This removes code duplication between summon and the Service
class toposort.
* Declaring dependency loops is still caught at class declaration
time.
* The asymptotic and actual run-time for the acyclicity checks has
been improved.
=> Simplify service ordering

aioxmpp/utils.py, tests/test_utils.py
`namespaces` now is an instance of the new class `Namespaces`, it checks that namespaces don't get two names, that a short-hand is not redefined and prohibits deleting a short-hand.
=> utils: Make namespaces do consistency checks

aioxmpp/misc/__init__.py, aioxmpp/misc/json.py, aioxmpp/xso/__init__.py, aioxmpp/xso/model.py, aioxmpp/xso/types.py, docs/api/changelog.rst, docs/index.rst, tests/misc/test_json.py, tests/xso/test_model.py, tests/xso/test_types.py
This PR mainly provides an "implementation" of XEP-0335, that is, adds an XSO for JSON containers. It is automatically registered as registered payload on PubSub items.
This mixes a few concerns, but it felt stupid to split the XSO changes which I needed for JSON stuff out into a separate PR; the other XSO changes are merely cleanup, fully following the "when touching it, clean it up" directive.
Fixes #271, starts work on #279.
=> JSON containers, XSO cleanup

aioxmpp/node.py, docs/conf.py
See the diff for an example.
**The only difference is in the source.** The rendered output is identical.
I think this might be much more readable. Shout out to @f3anaro for pointing this out to me.
If we decide to go for this, I suggest we follow the "clean what you’re touching" method instead of making an overhaul of all docstrings. I.e.: when you modify a function, adapt its docstring on the way. Just like we’re still in the process of moving to ``:param:`` instead of prose-only.
=> docs: decide whether to adopt Google Docstring style

aioxmpp/xso/types.py, tests/xso/test_types.py
This is in line with the standard (XEP-0198 § 3):
> The <enabled/> element MAY include a 'location' attribute to
> specify the server's preferred IP address or hostname
> (optionally with a port) for reconnection, in the form
> specified in Section 4.9.3.19 of RFC 6120 (i.e.,
> "domainpart:port", where IPv6 addresses are enclosed in square
> brackets "[...]" as described in RFC 5952 [6])
Fixes #290. Thanks @Terbau.
=> Support omission of port number in connection location specifier (backport to 0.10.0)

setup.py
lxml dropped support for Python 3.4 in version 4.4.
=> Fix lxml dependency declaration for Python < 3.5

aioxmpp/xml.py, tests/test_xml.py
This fixes an oversight where namespace URIs whose prefix has
been re-bound would not be removed from _curr_ns_map. That leads
to the prefix/namespace not being re-declared if the namespace was
declared further up in the hierarchy, but the prefix used in the
initial declaration was re-bound in-between.
Please see the added test cases for example situations.
Fixes #295.
=> xml: fix serialisation of re-ocurring nested namespaces

aioxmpp/xml.py, aioxmpp/xso/model.py, docs/api/changelog.rst, tests/test_xml.py, tests/xso/test_model.py
The old name used the weird non-verb "unparse". The new name uses
the proper `xso_` prefix reserved for library methods and attributes
on XSOs.
=> xso: rename unparse_to_sax to xso_serialise_to_sax

examples/echo_bot_im.py
In contrast to the classic echo_bot.py example, this auto-enables
and uses message carbons.
Fixes #318.
=> Add IM-based echo bot example

aioxmpp/muc/self_ping.py, tests/muc/test_self_ping.py
If the remote server is unreachable network-wise, we cannot know
whether we have been removed. In addition, a rejoin will fail
deterministically.
It is thus better to stay in the undecided pinging state (treat it
like a timeout): this will allow us to wait for a rejoin until we
know more about the current state and the server is actually
reachable again.
See-Also: https://github.com/xsf/xeps/pull/834
See-Also: #312
=> muc: treat remote server unreachability like timeout self-ping

aioxmpp/xso/types.py, docs/api/changelog.rst, tests/xso/test_types.py
Previously, the code would force coercion of the value through
the *nested* type (in most cases, String) first even if the value
was already an enumeration member. This obviously breaks because
the enumeration member is an instance of the Enumeration and not of
any other type.
This bug occurs only if deprecate_coerce is *false*, because
otherwise there was an additional check for enum membership in the
code path.
=> xso: fix assignment of enum members when only allow_coerce is true

aioxmpp/protocol.py, aioxmpp/testutils.py, docs/api/changelog.rst, tests/test_protocol.py, tests/test_testutils.py
The idea behind this is that this allows us to create an XMLStream
early and configure it (e.g. with future language settings, or
namespaces or whatever) before passing it down to the place where
the actual stream negotiation happens.
While we could instead pass down the future, that would be more
error-prone (and less flexible) than passing down the XMLStream
itself.
=> protocol: add support for multiple and late-created features_future:s

aioxmpp/muc/service.py, docs/api/changelog.rst, tests/muc/test_service.py
Without this, there is no simple way for users of the Room object
to obtain presence updates from occupants. While they could
install a global presence filter, that is highly undesirable.
The previous code would only emit on_presence_changed if the `show`
or `status` of the presence had changed. However, with custom
presence payloads, other attributes can be as or even more
interesting than that.
Fixes #341.
=> muc: always emit on_presence_change on presence updates
